dist: bionic
language: python

python: 3.6

addons:
  apt:
    packages:
      - tree

matrix:
  fast_finish: true
  include:
    - name: Python 2.7.18 target
      env:
        - TARGET_PYTHON_URL=https://github.com/equinor/portable-pythons/raw/master/bionic/bionic_cp27_18.tar.xz
        - TARGET_PYTHON_DIR=bionic_cp27_18
        - TARGET_PYTHON_VERSION="Python 2.7.18"
        - RELEASE=release-py27.yml

    - name: Python 3.8.3 target
      env:
        - TARGET_PYTHON_URL=https://github.com/equinor/portable-pythons/raw/master/bionic/bionic_cp38_3.tar.xz
        - TARGET_PYTHON_DIR=bionic_cp38_3
        - TARGET_PYTHON_VERSION="Python 3.8.3"
        - RELEASE=release-py38.yml

before_install:
  # Prepare komodo environment
  - virtualenv -ppython3 /tmp/kmd-venv
  - KMD_PYTHON=/tmp/kmd-venv/bin/python

  # Prepare target python
  - pushd /tmp
  - wget $TARGET_PYTHON_URL
  - tar xvf $TARGET_PYTHON_DIR.tar.xz
  - PIP=/tmp/${TARGET_PYTHON_DIR}/bin/pip
  - popd

install:
  - $KMD_PYTHON -m pip install . pytest

before_script:
  - rm -r komodo
  - $KMD_PYTHON -c "import komodo;print(komodo.__file__);print(komodo.__version__)"

script:
  # Unit tests
  - $KMD_PYTHON -m pytest tests

  # Lint tests
  - $KMD_PYTHON -m komodo.lint examples/releases/unstable.yml examples/repository.yml
  - $KMD_PYTHON -m komodo.lint examples/releases/ecl.yml examples/repository.yml

  # Full integration test
  - |
    $KMD_PYTHON -m komodo.cli ci/travis/${RELEASE} ci/travis/repository.yml \
                --workspace /tmp/ws                                         \
                --prefix /tmp/pfx                                           \
                --release travis                                            \
                --renamer rename.ul                                         \
                --pip $PIP
  # Build libkmd.so for testing
  - ci/travis/build_lib.sh /tmp/pfx/travis

  - tree /tmp/pfx
  # Use built komodo
  - source /tmp/pfx/travis/enable
  - which python
  - python --version
  - python -c "import numpy;print(numpy.__file__)"
  - ci/travis/test_import_lib.py

  # Test that everything makes sense
  - '[[ "$(which python)" == "/tmp/pfx/travis/root/bin/python" ]]'
  - '[[ "$(python --version 2>&1)" == "${TARGET_PYTHON_VERSION}" ]]'
