dist: bionic
language: python

python:
  - '2.7'
  - '3.6'

env:
  matrix:
    - UNIT_TEST=1
    - LINT_TEST=1
    - INTEGRATION_TEST=1

addons:
  apt:
    packages:
      - patchelf
      # This is needed to compile x86 programs in one of the tests
      - gcc-multilib

matrix:
  allow_failures:
    - env: INTEGRATION_TEST=1

install:
  # Install komodo dependencies
  - pip install pytest
  - pip install .

before_script:
  - rm -r komodo
  - python -c "import komodo;print(komodo.__file__);print(komodo.__version__)"

script:
  - if [[ ! -z $UNIT_TEST ]]; then pytest tests ; fi

  - if [[ ! -z $LINT_TEST ]]; then python -m komodo.lint examples/releases/unstable.yml examples/repository.yml ; fi
  - if [[ ! -z $LINT_TEST ]]; then python -m komodo.lint examples/releases/ecl.yml examples/repository.yml ; fi

  - if [[ ! -z $INTEGRATION_TEST ]]; then bin/kmd examples/releases/ecl.yml examples/repository.yml --workspace /tmp/ws --prefix /tmp/pfx --release integration --renamer rename.ul; fi
