dist: trusty
language: python

python:
  - '2.7'

env:
  matrix:
    - UNIT_TEST=1
    - LINT_TEST=1
    - INTEGRATION_TEST=1

matrix:
  allow_failures:
    - env: INTEGRATION_TEST=1

install:
  # Install patchelf
  - git clone https://github.com/equinor/patchelf
  - pushd patchelf
  - ./bootstrap.sh
  - ./configure
  - make
  - sudo make install

  # Install komodo dependencies
  - pip install pytest
  - pip install .

before_script:
  - rm -r komodo
  - python -c "import komodo;print(komodo.__file__);print(komodo.__version__)"

script:
  - if [[ ! -z $UNIT_TEST ]]; then pytest tests ; fi

  - if [[ ! -z $LINT_TEST ]]; then python -m komodo.lint examples/releases/unstable.yml examples/repository.yml ; fi
  - if [[ ! -z $LINT_TEST ]]; then python -m komodo.lint examples/releases/ecl.yml examples/repository.yml ; fi

  - if [[ ! -z $INTEGRATION_TEST ]]; then bin/kmd examples/releases/ecl.yml examples/repository.yml --workspace /tmp/ws --prefix /tmp/pfx --release integration --renamer rename.ul; fi
